# https://yunohost.org/en/packaging_config_panels
# https://github.com/YunoHost/example_ynh/blob/master/config_panel.toml.example

version = "1.0"

[main]
name.en = "Main configuration"
name.fr = "Configuration principale"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.is_free]
        ask = "This determines whether there is a star labeled **Free** on the login page?"
        type = "boolean"
        bind = "is_free:/var/www/__APP__/fiduswriter/configuration.py"

        [main.config.registration_open]
        ask = "Allow new user registration"
        type = "boolean"
        bind = "registration_open:/var/www/__APP__/fiduswriter/configuration.py"

        [main.config.password_login]
        ask = "Enable password-based login"
        type = "boolean"
        bind = "password_login:/var/www/__APP__/fiduswriter/configuration.py"

        [main.config.socialaccount_open]
        ask = "Enable social account login"
        type = "boolean"
        bind = "socialaccount_open:/var/www/__APP__/fiduswriter/configuration.py"
